Fix Gradle duplicate jar failure when adding a test entity having a dependency already in the kit
Terracotta-OSS/terracotta-gradle-plugins pull request #31
Opened 2024-12-17 09:13 UTC by mathieucarbou

Error example:

```
* What went wrong:
Execution failed for task ':system-tests:management:galvanKitPreparation'.
> Entry server/plugins/lib/voltron-proxy-server-5.10-SNAPSHOT.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.4/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

2025-01-07 17:43 UTC, chrisdennis requested changes

2025-01-07 17:43 UTC, chrisdennis commented on src/main/java/org/terracotta/build/plugins/AbstractKitTestingPlugin.java
> +        spec.filesMatching("**/*.jar", fcd -> {
I think what you're doing is okay... but I think the comment isn't correct. We don't know what dependency strategy is going to be used. I think it's safe to exclude here because of what we're building though.

2025-01-08 08:47 UTC, mathieucarbou commented on src/main/java/org/terracotta/build/plugins/AbstractKitTestingPlugin.java
> +        spec.filesMatching("**/*.jar", fcd -> {
Ah! That's right... Did not thing of that!

2025-01-08 14:58 UTC, chrisdennis approved these changes

2025-01-08 14:59 UTC, merged